config/routes.rb
Rails.application.routes.draw do

  resources :categories, :foods, :carts, :shopcarts

  ActiveAdmin.routes(self)
  devise_for :users
  
  root 'categories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.admin?
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :food
  belongs_to :shopcart
end

app/models/category.rb
class Category < ApplicationRecord
 has_many :foods
 has_attached_file :image,
                    styles: { medium: '300x350>', thumb: '100x100>'},
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image, 
                    content_type: ['image/jpeg', 'image/gif', 'image/png']
end

app/models/food.rb
class Food < ApplicationRecord
 belongs_to :category
 has_many :food
 has_attached_file :image,
                    styles: { medium: '300x300>', thumb: '100x100>'},
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image, 
                    content_type: ['image/jpeg', 'image/gif', 'image/png']
end

app/models/shopcart.rb
class Shopcart < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :carts
end

app/models/user.rb
class User < ApplicationRecord
  # has_many :carts
  has_many :shopcarts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 validates :address, presence: true
 validates :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :current_cart, :current_user, :calc

  private

  
  def logged_in_user
    unless logged_in?
      flash[:danger] = 'Please log in'
      redirect_to login_url
    end
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone, :address])
  end

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end

  def calc
    if user_signed_in?   
      cart_total = 0
      current_user.shopcarts.each do |shopcart|
        shopcart.carts.each do |cart|
          cart_total += (cart.food.price * cart.count)
        end
      end
      return cart_total
    else 
     'Please log in'
    end  
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
  	@cart = Cart.all
  end

  def show
  	@cart = Cart.find(params[:id])
  end

  def create
     if Cart.find_by_food_id_and_shopcart_id(params[:cart][:food_id], params[:cart][:shopcart_id])
       @cart = Cart.find_by_food_id_and_shopcart_id(params[:cart][:food_id], params[:cart][:shopcart_id])
       @cart.count += params[:cart][:count].to_i
     else
       @cart = Cart.new(cart_params)
     end
     if @cart.save
       redirect_to :back
     else
       redirect_to root_path
     end
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    redirect_to :back
  end


  def cart_params
    params.require(:cart).permit(:food_id, :shopcart_id, :count)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all
  end

  def show
  	@category = Category.find(params[:id])
    if user_signed_in?
     @shopcart = Shopcart.find_by_user_id_and_category_id(current_user.id, @category.id)
    else
      redirect_to new_user_session_path
    end
  end

  private 

   def category_params
    params.require(:category).permit(:name, :desc)
   end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
  	foods = Food.all
  end

  def show
  	@food = Food.find(params[:id])
  end

  private 

   def food_params
    params.require(:food).permit(:name, :desc, :price, :category_id)
   end
end

app/controllers/shopcarts_controller.rb
class ShopcartsController < ApplicationController
  def show
	# @shopcart = Shopcart.find_by_user_id_and_category_id(current_user, @category.id)
  end

  def create 
  	@shopcart = Shopcart.create!(user_id: current_user.id, category_id: params[:cat])
  	if @shopcart.save 		
  		redirect_to :back
  	else 
  		redirect_to root_path
  	end
  end

  def index 
  	@shopcarts = Shopcart.all 
  end

  def food_params
    params.require(:shopcart).permit(:user_id, :category_id)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/shopcarts_helper.rb
module ShopcartsHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/destroy.html.erb
<h1>Carts#destroy</h1>
<p>Find me in app/views/carts/destroy.html.erb</p>

app/views/carts/index.html.erb
<h1>Carts#index</h1>
<p>Find me in app/views/carts/index.html.erb</p>

app/views/carts/show.html.erb
<h1>Carts#show</h1>
<p>Find me in app/views/carts/show.html.erb</p>

app/views/categories/index.html.erb
  <center>
  	<div class="row row-category">
  		<div class="col-xs-6 col-md-3">

  			<h1> Заведения </h1>
  			<hr></hr>
  			<% @categories.each do |category|%>
  		</div>
  	</div>
 
  	<div class="">
  		<div class="col-md-6">
  			<div class="thumbnail">
  				<p>Название: <b><%= category.name %></b></p>
  				<p>Действие: <b><%= link_to 'Посмотреть меню', category_path(category.id) %></b></p>
  				<p><%= image_tag category.image.url(:medium) %></p>
  				<% end %>
  			</div>
  		</div>
  	</div>
  </center>	

app/views/categories/show.html.erb
<center>
<div class="row">
  <div class="col-xs-6 col-md-3">
  </div>
</div>
</center>

<h1> Меню для заведения "<%= @category.name %>" </h1>
  <a id="opencart">
  	<% if @shopcart == nil %>
		 <%= link_to 'Создать корзину', shopcarts_path(cat: @category.id), method: :post, class: 'btn btn-default' %>
	<% end %>
  </a>

<% @category.foods.each do |f| %> 
	<div class="">
	<div class="col-md-3">
	<div class="thumbnail">
		<p>Name:<b> <%= f.name %></b></p>
		<p>Description:<b> <%= f.desc %></b></p>  
		<p>Price: <b><%= f.price.to_i %></b></p>
		<p><%= image_tag f.image.url(:medium) %></p>
		<% if @shopcart == nil %>
		 
		<% else %>
		<center><p><%= link_to "Add to Cart", carts_path(cart: {:food_id => f.id, count: 1, shopcart_id: @shopcart.id}), :method => :post, id: "add_cart_#{f.id}", class: "btn btn-default" %></p></center>
		<% end %>
	</div>
	</div>
	</div>

<% end %>


	<% if @shopcart != nil %>
		<div class="basket">
    <h4>
      <span class="glyphicon glyphicon-large glyphicon-shopping-cart" aria-hidden="true">Cart</span>
    </h4>
      <% if user_signed_in? %>
       	<% @shopcart.carts.each do |cart| %>
	        <div>Название: <b><%= cart.food.name %></b></div>
	        <div>Цена: <b><%= cart.food.price %></b></div>
	        <div>Кол-во: <b><%= cart.count %></b></div>
	        <%= link_to 'Удалить', cart, method: :delete %>
	    <% end %>    
        <hr></hr> 
    <table>
      <tr>
        <th>Сумма</th>
        <th>Цена</th>
      </tr>
      <tr>
        <td colspan="2">Всего: </td>
        <td><%= calc.to_i %></td>
      </tr>
      <% else %>
       <b>Что-бы купить сперва <%= link_to 'зарегистрируйтесь', new_user_session_path %></b>
      <% end %>
    </table>
  </div>
  <% end %>

app/views/foods/index.html.erb
<center>
<div class="row">
  <div class="col-xs-6 col-md-3">
  </div>
</div>
</center>
<h1> Все блюда </h1>
<hr>
<hr>

<% Food.all.each do |f| %> 
	<div class="">
	<div class="col-md-3">
	<div class="thumbnail">
		<p>Name:<b> <%= f.name %></b></p>
		<p>Description:<b> <%= f.desc %></b></p>  
		<p>Price: <b><%= f.price.to_i %></b></p>
		<p><%= image_tag f.image.url(:medium) %></p>
		<center><p><%= link_to "Add to Cart", carts_path(cart: {:food_id => f.id, user_id: current_user, count: 1}), :method => :post, class: "btn btn-default" %></p></center>
	</div>
	</div>
	</div>

<% end %>

app/views/foods/show.html.erb
<h1>Foods#show</h1>
<p>Find me in app/views/foods/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodsmarket</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <nav class="navbar navbar-default" style="background: white">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a <%= link_to 'Foods', foods_path %></a></li>
        <li><a href="#">Contacts</a></li>
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">
            Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
          </p>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                <li><a href="#">View orders</a></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>